#
## Travis Continuous Integration configuration file.
## https://travis-ci.org/leogps/ItunesLibraryParser
#
jdk:
  - oraclejdk8
  - openjdk7
language: java
before_install:
  - sudo apt-get update -q
  - sudo apt-get install git -y
  - git clone https://github.com/leogps/ItunesLibraryParser.git
  - cd ItunesLibraryParser
  - mvn clean install
  - mvn install:install-file -Dfile="parser/target/com.gps.ilp-parser-2.0.0.jar" -DgroupId="com.gps" -DartifactId="ilp-parser" -Dversion="2.0.0" -Dpackaging="jar"
  - mvn install:install-file -Dfile="lib-runtime/ui.jar" -DgroupId="com.apple" -DartifactId="AppleJavaExtensions" -Dversion="1.6" -Dpackaging="jar"